# Generated by Django 3.0.8 on 2020-07-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productavailability',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productcategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productprice',
            new_name='price',
        ),
    ]
