# Generated by Django 3.0.8 on 2020-07-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200712_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
