# Generated by Django 3.0.8 on 2020-07-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200712_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='productname',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
