# Generated by Django 3.0.8 on 2020-07-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homepageinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('subtitile', models.CharField(max_length=40)),
                ('banner', models.ImageField(upload_to='')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
