# Generated by Django 3.0.8 on 2020-07-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepageinfo',
            old_name='subtitile',
            new_name='subtitle',
        ),
    ]
